### ISSUE TITLE
[Suggestion]: Compatibility with Things' Hardening Catalyst

### ISSUE THREAD

**Issue by zetachrome** [Fuzss/easyanvils#10]
### Suggestion (Required)

Launcher: Fabric

Easy Anvils 4.0.5
Things 0.2.20

Hardening Catalyst is an item that combines with any item with durability in an anvil to make it unbreakable.

I was playing on Medieval 1.19.2 Fabric and tried to combine a glass sword (twilight forest) and a hardening catalyst and it was not working. I tested with just Easy Anvils and Things, and I couldn't combine any item with Hardening Catalyst, modded or vanilla. I then took off easy anvils and the hardening catalyst worked fine; as a workaround for my Medieval world, I took off easy anvils, applied the catalyst, and re-added it.

I don't know if it worked before the recent Medieval 1.19.2 v9 update (in other words, with different versions of either Things or easy anvils) as I just now tried to do this.

**Comment by Fuzss** [comment]
That's to be expected. Fabric is not very good when it comes to certain aspects of mod compatibility such as this due to the absence of many common events (so in this case there is no common event for changing the anvil mechanics so I had to create my own which a mod such as Things of course isn't aware of, Forge does this way better out of the box, so there is no issue there).
I'll create a patch for Things in Easy Anvils when I find the time.

**Comment by Fuzss** [comment]
Thanks for the report! Should be fixed in v4.0.7. Please reopen if it's not.
