### ISSUE TITLE
[Suggestion]: Config option to make second item not to be upside down in anvil visuals.

### ISSUE THREAD

**Issue by murao-kun** [Fuzss/easyanvils#16]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.6

### Notes (Required)

Second item is upside down in anvil visuals.
![image](https://user-images.githubusercontent.com/110398598/210265111-19d01fa6-930d-433c-b0e8-9d1347d174f1.png)

**Comment by Fuzss** [comment]
Thanks for reporting. This is intentional.

**Comment by murao-kun** [comment]
@Fuzss can we turn this report to suggestion?

**Comment by Fuzss** [comment]
The problem is anvils can only be placed facing two directions, not in all four cardinal directions (means placing an anvil facing south or north will have the same result).

So if both items face the same way they'll always face up or down from a certain direction and there is no way of changing that in-game. Having the items face different directions is a good compromise I think.

**Comment by murao-kun** [comment]
I see now. Yeah, that totally bad thing on vanilla mc side. Thank you for explaining!

**Comment by murao-kun** [comment]
Not sure if that can work, but you can use the thing you used in easy crafting tables, when items rotating to direction from you are looking at.
