### ISSUE TITLE
[Crash]: Crashed with Better Furnance Reforged

### ISSUE THREAD

**Issue by RedBeast1959** [Fuzss/easyanvils#2]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2 - Forge 43.1.32

### Mod Version (Required)

EasyAnvils-v4.0.1-1.19.2-Forge.jar

### Notes (Required)

I put Easy Anvil into my huge 260+ custom modpack and it worked surprisingly well...
...until I put Better Furnance Reforged(https://www.curseforge.com/minecraft/mc-mods/better-furnaces-reforged) into modpack.

It immediately crashed when launching the game. According to Not Enough Crash mod's report file, suspected mods were Puzzles Lib and Easy Anvils. I still don't understand why furnance mod crashed with anvil mod.

PuzzlesLib-v4.3.9-1.19.2-Forge.jar
EasyAnvils-v4.0.1-1.19.2-Forge.jar
BetterFurnacesReforged-1.19.2-1.0.2.jar

### Crash Report (Required)

https://gist.github.com/RedBeast1959/d442e2c215d80d40aef7dac82a95f711

### latest.log (Optional)

https://gist.github.com/RedBeast1959/d0f92e674aa367cace8230665c43369b

**Comment by Fuzss** [comment]
This isn’t related to Better Furnace, it’s a coincidence. 

Does the crash happen consistently?

**Comment by RedBeast1959** [comment]
Yep. Constant crashed with Better Furnance mod. Without it, game works fine.

**Comment by Fuzss** [comment]
Also with just the three mods and nothing else?

PuzzlesLib-v4.3.9-1.19.2-Forge.jar
EasyAnvils-v4.0.1-1.19.2-Forge.jar
BetterFurnacesReforged-1.19.2-1.0.2.jar

**Comment by Fuzss** [comment]
Ok, found what's going on. Better Furnaces crashes the Forge event for registering content (blocks/items/etc), so my stuff in Easy Anvils doesn't exist when I need it during client setup.

Not sure why Forge decides to still let the game launch, with registries reverted to their vanilla state...
The error can only be seen in the latest.log file with just Better Furnaces installed since all exceptions are caught.

Would be great if you could just forward this issue to the Better Furnaces dev, the logs you provided should be enough for them to figure it out.

**Comment by RedBeast1959** [comment]
Wow, you found pesky bug's ground zero so easily! Thank you for your help. I'll make sure to inform this problem to B.F dev tomorrow. But right now, I need to sleep XD

**Comment by RedBeast1959** [comment]
Update: https://github.com/Wilyicaro/BetterFurnacesReforged/issues/59#issuecomment-1272557538

**Comment by Fuzss** [comment]
Made some more comments over there, if that's not enough it is how it is. The issue has nothing to do with any of my mods. Better Furnance Reforged crashes with a bunch of other mods, too (also tested with Storage Drawers, Quark).
